# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='echo.proto',
  package='',
  serialized_pb='\n\necho.proto\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04info\x18\x01 \x02(\t\"\x1c\n\x0c\x45\x63hoResponse\x12\x0c\n\x04info\x18\x01 \x02(\t2,\n\x04\x45\x63ho\x12$\n\x05Hello\x12\x0c.EchoRequest\x1a\r.EchoResponse')




_ECHOREQUEST = descriptor.Descriptor(
  name='EchoRequest',
  full_name='EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='info', full_name='EchoRequest.info', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=41,
)


_ECHORESPONSE = descriptor.Descriptor(
  name='EchoResponse',
  full_name='EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='info', full_name='EchoResponse.info', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=71,
)



class EchoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHOREQUEST
  
  # @@protoc_insertion_point(class_scope:EchoRequest)

class EchoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ECHORESPONSE
  
  # @@protoc_insertion_point(class_scope:EchoResponse)


_ECHO = descriptor.ServiceDescriptor(
  name='Echo',
  full_name='Echo',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=73,
  serialized_end=117,
  methods=[
  descriptor.MethodDescriptor(
    name='Hello',
    full_name='Echo.Hello',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    options=None,
  ),
])

class Echo(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ECHO
class Echo_Stub(Echo):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ECHO

# @@protoc_insertion_point(module_scope)
